### ISSUE TITLE
Dependencies not able to be retrieved from S3 when loading test plugin

### ISSUE THREAD

**Issue by tbergen1** [BuildFire/sdk#233]
I uploaded my plugin through the buildfire dev portal.  When I go to check it out in my test app it is broken.  The chrome logs show that there are a variety of failed GET requests to the S3 locations that my dependencies (ui-router, etc) have been stored in.  I followed the upload tutorial video to the letter, so I am not sure the cause of this.

![buildfire failed network](https://cloud.githubusercontent.com/assets/8553822/16711437/5dccbe1a-4629-11e6-93c3-029910f6fbdb.png)

**Comment by DanielHindi** [comment]
Hello,
Based on the logs I see. I believe you put your assets in the shared SDK folders. Read more here https://github.com/BuildFire/sdk/wiki/How-to-create-a-Plugin#so-where-do-i-put-my-resources-and-assets

Basically, all your dependencies should be in your Control and Widget folders. Furthermore, the Control and Widget shouldnt share assets.

The reason for this is because when your plugin is uploaded it gets split into two parts.  The Control goes to the control panel (app.buildfire.com) and the Widget goes to the App (both virtual and device)

Finally, while the SDK scripts folder is avaible in all the environments. Your modified copy of the SDK isnt used.

Hope this helps.

**Comment by tbergen1** [comment]
Yeah, it did help.  Thanks.
