### ISSUE TITLE
Display Timer Stops When App is Minimized

### ISSUE THREAD

**Issue by waltergrio** [BuildFire/sdk#251]
Hello - we have a Timer (HH:MM:SS) that's displayed in our app and it works well.  However, when you minimize the app and/or visit a different app, the Timer stops and doesn't start again until you maximize the app.  Any ideas on how we can get the Timer to display accurately when we maximize the app again?  Thanks!

**Comment by DanielHindi** [comment]
This is what happens when you dont have background execution in place. You can add this in with Features in your plugin.json. 
However, that may be a bit overkill. You can fix this by design. I would guess that you have a time span that is continuously decreasing. This is a problem when you need continuous execution. A better way may be to have a Start Time Stamp and continuously calculate the the difference between `Date.now()` and the the Start time stamp

Other topics that may help are:

- [BuildFire Services](https://github.com/BuildFire/sdk/wiki/BuildFire-Widget-Services). This is code that will run in the background of the app even if your plugin has navigated away. 
- [Local Notification](https://github.com/BuildFire/sdk/wiki/Buildfire-Local-Notifications-API): To schedule a future notification even if the app is killed

Hope this helps

**Comment by waltergrio** [comment]
Thanks @DanielHindi.  We'll give it a shot!
