### ISSUE TITLE
Control Panel - App Name

### ISSUE THREAD

**Issue by waltergrio** [BuildFire/sdk#259]
Sorry if I missed this in the documentation, but how do you delete and/or rename an app on your account?  There's a dropdown on top of the control panel where I can create a new app, but I didn't see how I could modify the name of an existing one (or delete one).  Thanks.

**Comment by DanielHindi** [comment]
These questions are usually better asked on a non-tech support channel like the Control Panel chat or support@buildfire.com. However, I believe you may be getting misled by the multiple names referring to your app in the system in [Appearance] and [Publish info]
There is the name of your app. 
Example "World Health Organization"
Then there is the app icon name. since "World Health Organization" is too large you might change it to "W.H.O."
You also may want to change the iOS version form the Android version, you can do so in Settings > Publish Information

Hope this helps.

* the support team can walk you through it if you'd like

**Comment by waltergrio** [comment]
Thanks @DanielHindi. I was actually referring to the one at the very top.  I'll send it to support.

![app-name](https://cloud.githubusercontent.com/assets/21219622/18419255/97eca2b8-7824-11e6-8eaf-01816e8ad656.jpg)
