### ISSUE TITLE
Weinre Debugger Fixes my Issue making it incredily difficult to debug a scrolling glitch

### ISSUE THREAD

**Issue by tbergen1** [BuildFire/sdk#295]
This isn't really an issue with the SDK, but it is a problem I have been wrestling with for a while now.  Essentially I customized a plugin that loads a post from an RSS Feed and displays it.  When I enter into this plugin on iOS devices the vertical scroll doesn't work.  I have tried every combination I can think of/find using overflow, settings heights of containers, using -webkit-scroll attributes, but nothing seems to work.  The main problem is that I am essentially doing all of this in an amazingly tedious manner as every time I load the weinre debugger for the plugin and click on an element within the DOM list it provides, the problem magically fixes itself.  Do you have any ideas why this would be and could the scrolling glitch potentially be a product of the previewer rather than the code itself?

**Comment by DanielHindi** [comment]
Have you tried disabling the theme using
`<meta name="buildfire" content="disableTheme">`
ref: https://github.com/BuildFire/sdk/wiki/BuildFire-MetaTags#buildfire-metatags

**Comment by tbergen1** [comment]
Nope. I haven't tried that.  I will try it later and report back.  Thanks.

**Comment by tbergen1** [comment]
@DanielHindi Disabling the theme did not work.  Would a Buildfire theme have an effect on scrolling in iOS.  Just to be clear too, this scrolling issue is only present on one of the plugins I customized.  I customized another instance of the same plugin and it scrolls perfectly fine.  The problem is I can't debug it in an easy manner since the weinre debugger fixes the problem immediately when I mouse over a DOM element in the tree when that plugin is fully loaded in the debugger.

**Comment by DanielHindi** [comment]
Since I didnt write the code i'm shooting in the dark here. But what I would do is start stripping everything out until it works. Then a CSS files , JS files an any other one at a time to see whats causing it. Basically process of elimination

**Comment by ianblair44** [comment]
For Future Reference:

"The issue is that iOS versions 8+ have a native bug in their scroll.  This bug arises from the fact that iOS tries to make some heavy oThe issue is that iOS versions 8+ have a native bug in their scroll.  This bug arises from the fact that iOS tries to make some heavy optimizations to scroll that causes conflicts.  These heavy optimizations, combined with the right kind of circumstance (what seems to be the loading of dynamic content into a scrollable element) can cause the container not to recognize that its bounds have been exceeded, thus not thinking it has to scroll.  This is why the plugins were not working on (iOS) devices, but was working perfectly fine on Android.  There is no "non-hacky" way to get around this, so it has to be patched to the best extent that it can be.  I have patched the scrolling issue, so the content will now scroll on load, but this has caused a conflict with the header carousel that was there as this carousel is not dynamically loaded into the page as the other page content is.ptimizations to scroll that causes conflicts.  These heavy optimizations, combined with the right kind of circumstance (what seems to be the loading of dynamic content into a scrollable element) can cause the container not to recognize that its bounds have been exceeded, thus not thinking it has to scroll.  This is why the plugins were not working on (iOS) devices, but was working perfectly fine on Android.  There is no "non-hacky" way to get around this, so it has to be patched to the best extent that it can be.  I have patched the scrolling issue, so the content will now scroll on load, but this has caused a conflict with the header carousel that was there as this carousel is not dynamically loaded into the page as the other page content is." - Tom

This could explain what was happening: Wiener might have fixed the scroll issue because it was forcing the CSS to recalculate. You can see if forcing the CSS to recalculate fixes it. 

https://css-tricks.com/forums/topic/my-site-will-not-scroll-vertically-in-safari/
https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/
https://weblog.west-wind.com/posts/2015/jun/05/ipad-scroll-issues-with-fixed-content
