### ISSUE TITLE
Audio pause event triggered by blog plugin's back button

### ISSUE THREAD

**Issue by noahmiller** [BuildFire/sdk#298]
A custom plugin is using the `buildfire.services.media.audioPlayer` service to play a radio stream.  In an app that also uses the standard blog plugin, the audio is unexpectedly pausing when the back button is tapped on a blog entry.

Steps to reproduce the bug:
1. Start audio playing via `buildfire.services.media.audioPlayer.play(...)`.  In our app, that's done by tapping a play button.
2. Navigate to the blog plugin, and tap a blog entry to bring up the detail view
3. Tap the back button in the navigation bar

Bug: the audio player is paused, and a `pause` event is sent to `buildfire.services.media.audioPlayer.onEvent`

Expected result: the background audio shouldn't pause when the user navigates around the app.

**Comment by abuturla** [comment]
@noahmiller Thank you for posting this; we are taking a look into it and will let you know when we have an update.

**Comment by abuturla** [comment]
@noahmiller It turns out that pausing the audio on clicking the back button to this plugin was a requested feature. The plugin in question (Media Center RSS Feed) can be used to play audio, and a user requested that we pause the audio when navigating away from from an item.

This isn't intuitive functionality so we'll go ahead and restore it to the original behavior; it will no longer pause the audio. We'll starting working on the changes and will let you know when it's implemented.

**Comment by abuturla** [comment]
@noahmiller A fix has been deployed to production. You should no longer experience the issue.

**Comment by NancyHaddad** [comment]
@noahmiller If you can please confirm the fix on your end by closing this ticket. Thank you. Best of luck to you!

**Comment by noahmiller** [comment]
Yes, thanks!  This is fixed now.
