### ISSUE TITLE
using php/sql instead of buildfire's Datastore

### ISSUE THREAD

**Issue by dhananjay1995** [BuildFire/sdk#320]
Hello!!
instead of using buildfire datastore..can i use sql php as backend ?? like creating webservices in php and calling them using ajax from app
Thanks!

**Comment by DanielHindi** [comment]
Absolutely. You can create any web service you want using any tech stack you want and as long as you can use AJAX to call it, you should be fine.

_One thing to look out for when testing on Web (like the control side of the plugin on the Control Panel) Your API needs to allow either CORS or JSONP to allow cross domain api calls._

**Comment by dhananjay1995** [comment]
nice, thank you Daniel !!

**Comment by dhananjay1995** [comment]
1 more question, 
can i build whole app by single custom plugin?? in my custom plugin, i'm using angular routing, controllers etc to switch between views and other functionality. thanks!!

**Comment by dhananjay1995** [comment]
and from where can i get pluginId, instanceId?? created my custom plugin, now on button click i want to open a new youtube plugin page... so i want to call that [youtubePlugin-master](https://github.com/BuildFire/youtubePlugin) index.
Thank you!

**Comment by DanielHindi** [comment]
> can i build whole app by single custom plugin?

Yes. However, there may be small draw backs for doing it that way. For example, any small update to your plugin will cause the app to download the entire plugin. Depending on how big the plugin is and how much you load upfront it may get bulky and slow. Just keep that in mind when you are designing your plugin
If you choose another path, such as multiple plugins that communicate with each other look into things like Shared Storage https://github.com/BuildFire/sdk/wiki/LocalStorage

> where can i get pluginId, instanceId?

So to get the current plugins info look into `buildfire.getContext`

# Plugin Lookup
to find other plugins in the current app 
https://github.com/BuildFire/sdk/wiki/Plugin-Instances

# Dynamic Data
Consider this, if you save the plugin instanceId of another plugin along with its icon and name. Your data may get stale because the app owner may change it without your reference getting updated. This is why in databases we use foreign keys as a reference so that we always join tables to get the latest information. In DataStore we have something called Dynamic Data lookup that helps you do the same thing for plugins 
https://github.com/BuildFire/sdk/wiki/How-to-use-the-Datastore-Dynamic-Data

# Examples
To see all this in action you can look at our Folder Plugin that basically looks up other plugins in the app, keeps track of them in its own list and then navigates to it
https://github.com/BuildFire/folderPlugin
or a simpler version is
https://github.com/DanielHindi/folderPlugin

***

There is a lot to read here but I hope it all makes sense.

**Comment by dhananjay1995** [comment]
can you please tell me exactly what i have to send buildfire.getContext... to get pluginData.

**Comment by dhananjay1995** [comment]
can i remove 
![screenshot from 2017-02-11 16 59 38](https://cloud.githubusercontent.com/assets/20607700/22853415/b92b9b58-f07b-11e6-9085-ef6c767d91e9.png)
blue burger sidemenu from my app?? coz i have made single plugin with internal routing...when i visit third page nd click on Home from sidemenu it stays on that page only.

**Comment by dhananjay1995** [comment]
window.localStorage.getItem('appContext'); giving me same pluginId, InstanceId on every plugin... :/

**Comment by DanielHindi** [comment]
Not sure how that was set in your localstorage but all you need to do is call
````
buildfire.getContext(callback);
````

**Comment by DanielHindi** [comment]
Also as a side note. Please try to open up separate tickets for different issues this way we wont lose track of any questions you may ask.  Thank you

**Comment by dhananjay1995** [comment]
Nice, thanks!!
