### ISSUE TITLE
Is there any way to make make the design changes dynamically in a plugin?

### ISSUE THREAD

**Issue by MaggieMacwell** [BuildFire/sdk#352]
Is there any way to make make the design changes dynamically in a plugin? 

For ex. If we have created one tab in a plugin on widget side and if we want to develop tab who's shape, size color and text color changed.

So if you can share me the example please share or provide me some ideas.

**Comment by DanielHindi** [comment]
You definatly can. Most of our plugins change design settings on the control side so the app owner sets the design for everyone. However, you can easily move that capability over to the user on the widget side so that each user may select their own design/layout. 

Unfortunately, I don't have an example plugin to show you. However, feel free to contact our pro services department proservices@buildfire.com if you need help implementing this feature 

Sounds like a really cool feature.

**Comment by DanielHindi** [comment]
closed due to inactivity
